import { createClient } from '@/lib/supabase/server';

export const dynamic = 'force-dynamic';

// ── SKU helpers ────────────────────────────────────────────────────────────
// Product-level SKU is generated by the DB trigger (generate_product_sku)
// which uses MAX() to find the next safe sequence — collision-free.

function normalizeColor(color) {
  return (color || 'DEFAULT')
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

// ── Helpers ────────────────────────────────────────────────────────────────
async function requireAdmin(supabase, user) {
  const { data: profile } = await supabase
    .from('user_profiles')
    .select('role')
    .eq('id', user.id)
    .single();
  return profile?.role === 'admin';
}

function mapVariant(v) {
  return {
    id: v.id,
    sku: v.sku,
    color: v.color,
    price: v.price,
    stockQuantity: v.stock_quantity,
    dimensions: v.dimensions,
    material: v.material,
    weight: v.weight,
    imageUrl: v.image_url,
    isActive: v.is_active,
    productId: v.product_id,
  };
}

// ── POST /api/products — create product + variants ────────────────────────
export async function POST(request) {
  const supabase = await createClient();

  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
  if (!(await requireAdmin(supabase, user))) return Response.json({ error: 'Forbidden' }, { status: 403 });

  const productData = await request.json();
  const variants = productData?.variants || [];
  const firstVariant = variants[0];
  const isActive = productData?.status === 'active';

  // SKU is auto-generated by the DB trigger — do not pass sku here.
  const { data: product, error: productError } = await supabase
    .from('products')
    .insert([{
      name: productData.name,
      description: productData.description,
      brand: productData.brand || null,
      category: productData.category,
      base_price: parseFloat(firstVariant?.price ?? 0),
      image_alt: productData.imageAlt,
      is_active: isActive,
    }])
    .select()
    .single();

  if (productError) return Response.json({ error: productError.message }, { status: 500 });

  const variantRows = variants.map(v => ({
    product_id: product.id,
    name: v.color || productData.name,
    sku: `${product.sku}-${normalizeColor(v.color)}`,
    color: v.color,
    price: parseFloat(v.price || 0),
    stock_quantity: parseInt(v.stock_quantity || 0),
    dimensions: v.dimensions || null,
    material: v.material || null,
    weight: v.weight ? String(v.weight) : null,
    image_url: v.image || null,
  }));

  const { data: insertedVariants, error: variantsError } = await supabase
    .from('product_variants')
    .insert(variantRows)
    .select();

  if (variantsError) return Response.json({ error: variantsError.message }, { status: 500 });

  const mappedVariants = (insertedVariants || []).map(mapVariant);
  const prices = mappedVariants.map(v => v.price).filter(Boolean).sort((a, b) => a - b);
  const totalStock = mappedVariants.reduce((s, v) => s + (v.stockQuantity || 0), 0);

  return Response.json({
    data: {
      id: product.id,
      name: product.name,
      brand: product.brand,
      sku: product.sku,
      category: product.category,
      price: prices[0] ?? 0,
      stock: totalStock,
      status: product.is_active ? 'active' : 'inactive',
      description: product.description,
      imageAlt: product.image_alt,
      image: mappedVariants[0]?.imageUrl || null,
      variants: mappedVariants,
    },
  });
}

// ── DELETE /api/products — bulk soft-archive { ids: [...] } ──────────────
export async function DELETE(request) {
  const supabase = await createClient();

  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
  if (!(await requireAdmin(supabase, user))) return Response.json({ error: 'Forbidden' }, { status: 403 });

  const { ids } = await request.json();
  if (!ids?.length) return Response.json({ error: 'ids required' }, { status: 400 });

  // Soft-delete: mark as archived instead of hard delete so order history stays intact
  const { error } = await supabase
    .from('products')
    .update({ is_archived: true })
    .in('id', ids);

  if (error) return Response.json({ error: error.message }, { status: 500 });

  // Remove from active carts and wishlists
  await supabase.from('cart_items').delete().in('product_id', ids);
  await supabase.from('wishlist_items').delete().in('product_id', ids);

  return Response.json({ success: true });
}
