
import CatalogInteractive from './components/CatalogInteractive';

// Force dynamic rendering to prevent prerendering during build
export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Furniture Catalog - VirtualFurnish',
  description: 'Browse our complete furniture collection with detailed product information and pricing'
};

const mockProducts = [
  { id: '1', name: 'Modern L-Shape Sofa', category: 'Sofa', basePrice: 24999.0, sku: 'SOF-001', imageUrl: 'https://images.unsplash.com/photo-1667584523303-5d9e6779382b', imageAlt: 'A modern brown L-shaped sofa.', description: 'Contemporary L-shaped sofa with premium fabric upholstery and solid wood frame. Perfect for modern living rooms.', dimensions: '220cm x 150cm x 85cm', material: 'Fabric', variants: [ { id: 'v1-1', name: 'Brown', sku: 'SOF-001-BRN', price: 24999.0, stockQuantity: 15 } ] },
  { id: '2', name: 'Executive Office Chair', category: 'Chair', basePrice: 8999.0, sku: 'CHR-002', imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_11b201e6f-1764832795834.png', imageAlt: 'A black leather executive office chair.', description: 'Ergonomic executive office chair with high back support and adjustable armrests. Features premium leather upholstery.', dimensions: '65cm x 70cm x 120cm', material: 'Leather', variants: [ { id: 'v2-1', name: 'Black', sku: 'CHR-002-BLK', price: 8999.0, stockQuantity: 28 } ] },
  { id: '3', name: 'Solid Wood Dining Table', category: 'Table', basePrice: 18500.0, sku: 'TBL-003', imageUrl: 'https://images.unsplash.com/photo-1674797878035-4fdb18d3343b', imageAlt: 'A solid oak dining table.', description: 'Handcrafted solid oak dining table with natural wood finish. Seats 6-8 people comfortably.', dimensions: '200cm x 100cm x 75cm', material: 'Solid Oak Wood', variants: [ { id: 'v3-1', name: 'Oak', sku: 'TBL-003-OAK', price: 18500.0, stockQuantity: 8 } ] },
  { id: '4', name: 'Queen Size Platform Bed', category: 'Bed', basePrice: 32000.0, sku: 'BED-004', imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_147093a9f-1764775756664.png', imageAlt: 'A gray queen size platform bed.', description: 'Modern platform bed with upholstered headboard and storage drawers. Queen size with sturdy slat support.', dimensions: '210cm x 160cm x 110cm', material: 'Fabric', variants: [ { id: 'v4-1', name: 'Gray', sku: 'BED-004-GRY', price: 32000.0, stockQuantity: 5 } ] },
  { id: '5', name: 'Glass Display Cabinet', category: 'Cabinet', basePrice: 15800.0, sku: 'CAB-005', imageUrl: 'https://images.unsplash.com/photo-1722078139141-279c26e08abb', imageAlt: 'A white glass display cabinet.', description: 'Elegant glass display cabinet with LED lighting and adjustable shelves. Perfect for showcasing collectibles.', dimensions: '90cm x 45cm x 180cm', material: 'Tempered Glass, MDF', variants: [ { id: 'v5-1', name: 'White', sku: 'CAB-005-WHT', price: 15800.0, stockQuantity: 12 } ] },
  { id: '6', name: 'Standing Computer Desk', category: 'Desk', basePrice: 12500.0, sku: 'DSK-006', imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_17b317373-1764840509664.png', imageAlt: 'A black standing computer desk.', description: 'Height-adjustable standing desk with electric motor. Features spacious work surface and cable management system.', dimensions: '140cm x 70cm x 75-120cm', material: 'Laminated Wood, Steel', variants: [ { id: 'v6-1', name: 'Black', sku: 'DSK-006-BLK', price: 12500.0, stockQuantity: 20 } ] },
  { id: '7', name: 'Velvet Accent Chair', category: 'Chair', basePrice: 6800.0, sku: 'CHR-007', imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_1fa73df78-1764795294797.png', imageAlt: 'A navy blue velvet accent chair.', description: 'Luxurious velvet accent chair with gold metal legs. Features deep button tufting and curved armrests.', dimensions: '75cm x 80cm x 85cm', material: 'Velvet, Metal', variants: [ { id: 'v7-1', name: 'Navy Blue', sku: 'CHR-007-BLU', price: 6800.0, stockQuantity: 18 } ] },
  { id: '8', name: 'Marble Coffee Table', category: 'Table', basePrice: 9999.0, sku: 'TBL-008', imageUrl: 'https://images.unsplash.com/photo-1622527561244-74e49a3878a1', imageAlt: 'A marble coffee table.', description: 'Contemporary coffee table with genuine marble top and gold metal base. Features elegant design.', dimensions: '120cm x 60cm x 45cm', material: 'Marble, Metal', variants: [ { id: 'v8-1', name: 'White Marble', sku: 'TBL-008-WHT', price: 9999.0, stockQuantity: 10 } ] },
  { id: '9', name: 'Recliner Sofa Set', category: 'Sofa', basePrice: 45000.0, sku: 'SOF-009', imageUrl: 'https://images.unsplash.com/photo-1705028877368-43d73100c1fd', imageAlt: 'A brown recliner sofa set.', description: 'Premium 3-seater recliner sofa with manual recline mechanism. Features genuine leather upholstery.', dimensions: '220cm x 95cm x 100cm', material: 'Genuine Leather', variants: [ { id: 'v9-1', name: 'Brown', sku: 'SOF-009-BRN', price: 45000.0, stockQuantity: 3 } ] },
  { id: '10', name: 'Bookshelf Cabinet', category: 'Cabinet', basePrice: 11200.0, sku: 'CAB-010', imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_1f25dd3de-1764684031226.png', imageAlt: 'An oak bookshelf cabinet.', description: 'Tall bookshelf cabinet with 5 adjustable shelves. Features sturdy construction and classic design.', dimensions: '80cm x 35cm x 200cm', material: 'Engineered Wood', variants: [ { id: 'v10-1', name: 'Oak', sku: 'CAB-010-OAK', price: 11200.0, stockQuantity: 14 } ] },
  { id: '11', name: 'Kids Study Desk', category: 'Desk', basePrice: 5500.0, sku: 'DSK-011', imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_177eda7c4-1764998661084.png', imageAlt: 'A pink kids study desk.', description: 'Colorful study desk designed for children with storage compartments and adjustable height.', dimensions: '100cm x 60cm x 65-75cm', material: 'MDF, Plastic', variants: [ { id: 'v11-1', name: 'Pink', sku: 'DSK-011-PNK', price: 5500.0, stockQuantity: 22 } ] },
  { id: '12', name: 'King Size Bed Frame', category: 'Bed', basePrice: 38500.0, sku: 'BED-012', imageUrl: 'https://images.unsplash.com/photo-1722604831167-8583e0772c5b', imageAlt: 'A black king size bed frame.', description: 'Luxury king size bed frame with leather headboard and LED lighting. Features hydraulic storage.', dimensions: '220cm x 200cm x 120cm', material: 'Leather, Solid Wood', variants: [ { id: 'v12-1', name: 'Black', sku: 'BED-012-BLK', price: 38500.0, stockQuantity: 4 } ] },
  { id: '13', name: 'Dining Chair Set', category: 'Chair', basePrice: 3200.0, sku: 'CHR-013', imageUrl: 'https://images.unsplash.com/photo-1707923745240-628a850ae237', imageAlt: 'A set of gray dining chairs.', description: 'Set of 2 modern dining chairs with fabric upholstery and wooden legs. Features comfortable padded seats.', dimensions: '45cm x 55cm x 90cm', material: 'Fabric, Wood', variants: [ { id: 'v13-1', name: 'Gray', sku: 'CHR-013-GRY', price: 3200.0, stockQuantity: 0 } ] },
  { id: '14', name: 'Console Table', category: 'Table', basePrice: 7800.0, sku: 'TBL-014', imageUrl: 'https://images.unsplash.com/photo-1722650363326-9dcd45f43742', imageAlt: 'A white console table.', description: 'Elegant console table with drawer storage and lower shelf. Perfect for entryways and hallways.', dimensions: '120cm x 35cm x 80cm', material: 'MDF, Wood', variants: [ { id: 'v14-1', name: 'White', sku: 'TBL-014-WHT', price: 7800.0, stockQuantity: 16 } ] },
  { id: '15', name: 'Wardrobe Cabinet', category: 'Cabinet', basePrice: 28000.0, sku: 'CAB-015', imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_19243aaf6-1764702217826.png', imageAlt: 'A brown wardrobe cabinet.', description: 'Spacious 3-door wardrobe with hanging rod, shelves, and drawers. Features mirror door and soft-close mechanism.', dimensions: '180cm x 60cm x 220cm', material: 'Engineered Wood', variants: [ { id: 'v15-1', name: 'Brown', sku: 'CAB-015-BRN', price: 28000.0, stockQuantity: 6 } ] }
];

export default function FurnitureCatalogPage() {
  return <CatalogInteractive initialProducts={mockProducts} />;
}